<a href="https://colab.research.google.com/github/joyangelai/Colabs-Vol-2/blob/main/encodeing_and_lG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Label Encoding

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [ ]:
#load dataset
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
## one hot encoder
encode = OneHotEncoder()

encode.fit_transform(df[["embark_town"]]).toarray()

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
# checking the cat names
encode.categories_

[array(['Cherbourg', 'Queenstown', 'Southampton', nan], dtype=object)]

In [ ]:
# encode using get dummies
encode2 = pd.get_dummies(df[["embark_town", "embarked"]],drop_first=True, dtype='int')
encode2

     embark_town_Queenstown  embark_town_Southampton  embarked_Q  embarked_S
0                         0                        1           0           1
1                         0                        0           0           0
2                         0                        1           0           1
3                         0                        1           0           1
4                         0                        1           0           1
..                      ...                      ...         ...         ...
886                       0                        1           0           1
887                       0                        1           0           1
888                       0                        1           0           1
889                       0                        0           0           0
890                       1                        0           1           0

[891 rows x 4 columns]

In [ ]:
#loading houseprice dataset
data = pd.read_csv("homeprices.csv")
data.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [ ]:
end1 = pd.get_dummies(data["town"], drop_first=True, dtype="int")
end1

    robinsville  west windsor
0             0             0
1             0             0
2             0             0
3             0             0
4             0             0
5             0             1
6             0             1
7             0             1
8             0             1
9             1             0
10            1             0
11            1             0
12            1             0

In [ ]:
merged_df = pd.concat([data, end1], axis=1)
merged_df

               town  area   price  robinsville  west windsor
0   monroe township  2600  550000            0             0
1   monroe township  3000  565000            0             0
2   monroe township  3200  610000            0             0
3   monroe township  3600  680000            0             0
4   monroe township  4000  725000            0             0
5      west windsor  2600  585000            0             1
6      west windsor  2800  615000            0             1
7      west windsor  3300  650000            0             1
8      west windsor  3600  710000            0             1
9       robinsville  2600  575000            1             0
10      robinsville  2900  600000            1             0
11      robinsville  3100  620000            1             0
12      robinsville  3600  695000            1             0

In [ ]:
#drop town column
del merged_df["town"]

merged_df.head()

   area   price  robinsville  west windsor
0  2600  550000            0             0
1  3000  565000            0             0
2  3200  610000            0             0
3  3600  680000            0             0
4  4000  725000            0             0

In [ ]:
#divide data into 2(features and label)

#X is our features/indepedent variables
X = merged_df.drop("price", axis=1)
X

    area  robinsville  west windsor
0   2600            0             0
1   3000            0             0
2   3200            0             0
3   3600            0             0
4   4000            0             0
5   2600            0             1
6   2800            0             1
7   3300            0             1
8   3600            0             1
9   2600            1             0
10  2900            1             0
11  3100            1             0
12  3600            1             0

In [ ]:
#dependent/label
y = merged_df["price"]

In [ ]:
#call the model
from sklearn.linear_model import LinearRegression

In [ ]:
#call/initialize the model
model = LinearRegression()

#train the model
model.fit(X,y)

LinearRegression()

In [ ]:
#predict the model
model.predict(X)

array([539709.7398409 , 590468.71640507, 615848.20468716, 666607.18125134,
       717366.15781552, 579723.71533004, 605103.20361213, 668551.92431735,
       706621.15674048, 565396.1513653 , 603465.38378843, 628844.87207052,
       692293.59277575])

In [ ]:
merged_df["price"]

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
print(round(model.score(X,y),2))

0.96

In [ ]:
#trying to predict unseen data

model.predict([[5000, 1, 0]])

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([869950.01075037])